from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

import networkx as nx


@dataclass(frozen=True)
class FunctionProfile:
    """Call-graph metrics for a Python function or method."""

    name: str
    fan_in: int
    fan_out: int
    betweenness: float
    is_critical: bool

    @property
    def risk_label(self) -> str:
        if self.betweenness >= 0.2 or self.fan_in >= 5:
            return "HIGH"
        if self.betweenness >= 0.1 or self.fan_in >= 3:
            return "MED"
        return "low"


def build_call_graph(src_dir: Path) -> nx.DiGraph[str]:
    """Run pyan3 against Python files in a source directory."""
    py_files = [str(path) for path in src_dir.rglob("*.py")]
    graph: nx.DiGraph[str] = nx.DiGraph()
    if not py_files:
        return graph

    command = ["pyan3", *py_files, "--no-defines", "--dot"]
    result = subprocess.run(  # noqa: S603,S607 - trusted CLI with fixed args.
        command,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"pyan3 failed: {result.stderr.strip()}")

    return parse_dot_to_digraph(result.stdout)


def parse_dot_to_digraph(dot_output: str) -> nx.DiGraph[str]:
    """Parse pyan3 dot output into a directed graph."""
    graph: nx.DiGraph[str] = nx.DiGraph()
    for raw_line in dot_output.splitlines():
        line = raw_line.strip()
        if "->" not in line or '"' not in line:
            continue
        parts = line.replace(";", "").split("->")
        if len(parts) != 2:
            continue
        source = parts[0].strip().strip('"')
        target = parts[1].strip().strip('"')
        if source != target and " " not in source and " " not in target:
            graph.add_edge(source, target)
    return graph


def analyze(
    src_dir: Path,
    top_n: int = 20,
    fan_in_threshold: int = 3,
    betweenness_threshold: float = 0.1,
) -> list[FunctionProfile]:
    """Analyze call-graph centrality and return the riskiest functions."""
    graph = build_call_graph(src_dir)
    if graph.number_of_nodes() == 0:
        return []

    betweenness = nx.betweenness_centrality(graph, normalized=True)
    profiles: list[FunctionProfile] = []
    for node in graph.nodes:
        fan_in = graph.in_degree(node)
        fan_out = graph.out_degree(node)
        centrality = betweenness.get(node, 0.0)
        profiles.append(
            FunctionProfile(
                name=node,
                fan_in=fan_in,
                fan_out=fan_out,
                betweenness=centrality,
                is_critical=fan_in >= fan_in_threshold
                or centrality >= betweenness_threshold,
            )
        )

    ordered = sorted(profiles, key=lambda item: (item.betweenness, item.fan_in))
    return list(reversed(ordered))[:top_n]


def format_report(profiles: list[FunctionProfile]) -> str:
    """Format call-graph metrics as a Markdown report."""
    lines = [
        "# Critical Functions",
        "",
        "> Auto-generated by `crag criticality --write`. Do not edit by hand.",
        "",
        "Functions marked critical have high fan-in or betweenness centrality.",
        "When editing them, full types, docstrings, and tests are mandatory.",
        "",
    ]
    critical = [profile for profile in profiles if profile.is_critical]
    non_critical = [profile for profile in profiles if not profile.is_critical]

    if critical:
        lines.extend(_format_section("Critical", critical))
    if non_critical:
        lines.extend(_format_section("Non-critical", non_critical))
    if not profiles:
        lines.append("No functions found.")
    return "\n".join(lines) + "\n"


def write_report(profiles: list[FunctionProfile], output_path: Path) -> None:
    """Write a Markdown criticality report."""
    output_path.write_text(format_report(profiles))


def print_table(profiles: list[FunctionProfile]) -> None:
    """Print a compact text table to stdout."""
    if not profiles:
        print("No functions found.")
        return
    header = (
        f"{'Function':<55} {'Fan-in':>8} {'Fan-out':>8} {'Centrality':>12} {'Risk':>8}"
    )
    print(header)
    print("-" * 96)
    for profile in profiles:
        print(
            f"{profile.name:<55} {profile.fan_in:>8} {profile.fan_out:>8} "
            f"{profile.betweenness:>12.4f} {profile.risk_label:>8}"
        )


def _format_section(title: str, profiles: list[FunctionProfile]) -> list[str]:
    lines = [f"## {title}", ""]
    lines.append("| Function | Fan-in | Fan-out | Centrality | Risk |")
    lines.append("| --- | ---: | ---: | ---: | --- |")
    for profile in profiles:
        lines.append(
            f"| `{profile.name}` | {profile.fan_in} | {profile.fan_out} | "
            f"{profile.betweenness:.4f} | {profile.risk_label} |"
        )
    lines.append("")
    return lines
